// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIik2BQVv9D1ugOOdXkD0ueusr7b_0xZI',
    appId: '1:397241128953:web:670a6ad1efd4e10880cf28',
    messagingSenderId: '397241128953',
    projectId: 'chatapp-33fc5',
    authDomain: 'chatapp-33fc5.firebaseapp.com',
    storageBucket: 'chatapp-33fc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Kq1e-P5qNMBbQz7P3BNi1Br2DpScyNY',
    appId: '1:397241128953:android:6369285b1ad1917e80cf28',
    messagingSenderId: '397241128953',
    projectId: 'chatapp-33fc5',
    storageBucket: 'chatapp-33fc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-37wWAXNbyDCJxmXEhzI-020Qx4Z_hY',
    appId: '1:397241128953:ios:eeef445c7d94191a80cf28',
    messagingSenderId: '397241128953',
    projectId: 'chatapp-33fc5',
    storageBucket: 'chatapp-33fc5.appspot.com',
    iosClientId: '397241128953-r8gbd4fd1nuhm0uc0pnsv3miv3ddkton.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2-37wWAXNbyDCJxmXEhzI-020Qx4Z_hY',
    appId: '1:397241128953:ios:4c8f69ca7be7dac980cf28',
    messagingSenderId: '397241128953',
    projectId: 'chatapp-33fc5',
    storageBucket: 'chatapp-33fc5.appspot.com',
    iosClientId: '397241128953-cmv93oepdgcohi73g8prk1i3r80chd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
